### ISSUE TITLE
fails on 4.3.0, works with FROM ubuntu:17.10

### ISSUE THREAD

**Issue by christiancadieux2** [rqlite/rqlite-docker#7]
4.3.0:
Ign:43 http://archive.ubuntu.com/ubuntu yakkety-backports/universe amd64 Packages
Reading package lists...
W: The repository 'http://security.ubuntu.com/ubuntu yakkety-security Release' does not have a Release file.
W: The repository 'http://archive.ubuntu.com/ubuntu yakkety Release' does not have a Release file.
W: The repository 'http://archive.ubuntu.com/ubuntu yakkety-updates Release' does not have a Release file.
W: The repository 'http://archive.ubuntu.com/ubuntu yakkety-backports Release' does not have a Release file.
E: Failed to fetch http://security.ubuntu.com/ubuntu/dists/yakkety-security/universe/source/Sources  404  Not Found [IPFROM ubuntu:17.10
: 91.189.88.162 80]
E: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/yakkety/universe/source/Sources  404  Not Found [IP: 91.189.88.161 80]
E: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/yakkety-updates/universe/source/Sources  404  Not Found [IP: 91.189.88.161 80]
E: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/yakkety-backports/main/binary-amd64/Packages  404  Not Found [IP: 91.189.88.161 80]
E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by otoolep** [comment]
Thanks for your report. I'm not a docker expert -- any suggestions on how to fix this?

**Comment by damianoneill** [comment]
Yakkety Yak is EOL in 2017.  The ppa's that image was built with are no longer available.  Easiest fix if you want to stay on 16 is to switch the base image to the LTS i.e. 

```sh
FROM ubuntu:xenial
```

**Comment by otoolep** [comment]
OK, I think the 4.5.0 Docker container is good now.

https://github.com/rqlite/rqlite-docker/commit/70ed48a86f0a375ac4decc21b4f03453065ac19d
